### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by RahulShahUI** [devfolioco/react-otp-input#102]
how can I add a label in relation with input element? it's giving below error while checking ADA compliance.

![image](https://user-images.githubusercontent.com/38944466/82798115-bc054880-9e95-11ea-9f19-d0e62b3856cd.png)

**Comment by aromalanil** [comment]
@apollonian 
I would like to work on this issue.

What I am planning to do is
- Wrap each input with a label with value `OTP Character no:${i}`
- Using `visuallyhidden` to hide the label for common users.

Please respond so I can work on this 😊

**Comment by borntofrappe** [comment]
Good morning.

Looking at the code for the [live demo](https://devfolioco.github.io/react-otp-input/), I'd say the issue could be fixed by adding a label to the four input elements describing the verification code. This can be done in a few ways:

- include a `<label>` element, but hide it with CSS

- add an `aria-label` attribute to the `<input>` element, with a string similar to "Verification code digit"

Considering the render logic of the `SingleOtpInput` component from [lib/index.jsx](https://github.com/devfolioco/react-otp-input/blob/master/src/lib/index.jsx), I would argue for the second approach. You can also pass through `props` the index of the input to have a string similar to "n-th digit for the verification code".

What do you think of this direction? I'll be more than glad to create a pull request :)

**Comment by apollonian** [comment]
> add an aria-label attribute to the <input> element, with a string similar to "Verification code digit"

This approach sounds good to me too, @borntofrappe! 
Do keep in mind that the value could also be any valid character when isInputNum is set as false for the label.

**Comment by borntofrappe** [comment]
If it can be a character as well, is it better to use a more general label, "Verification code alphanumeric character", or use `isInputNum` to distinguish between "digit" and "character"?

**Comment by borntofrappe** [comment]
I realized the question was less than important, and since the tone of the general label was quite too technical, I decided to use `isInputNum` boolean instead.

**Comment by apollonian** [comment]
@RahulShahUI This issue has been addressed with the latest release: [2.2.0](https://github.com/devfolioco/react-otp-input/releases/tag/v2.2.0). Accessibility report looking better now: https://wave.webaim.org/report#/https://devfolioco.github.io/react-otp-input
