### ISSUE TITLE
how to remove inline width from input

### ISSUE THREAD

**Issue by preeti-droom** [devfolioco/react-otp-input#118]
- **Steps to reproduce the issue**:

- **Relevant error messages and/or screenshots**:

**Comment by apollonian** [comment]
@preeti-droom You may override it by using the `inputStyle` prop.

**Comment by preeti-droom** [comment]
But i don't want to override the width using '!important' in css, if any other solution then let me know

**Comment by yasasvy** [comment]
how to apply styling to the individual default boxes after using OtpInput component?

**Comment by rtrembecky** [comment]
Hey, I have the same issue. In my case, I want to pass className from the Material UI styling solution (`useStyles`/`makeStyles`) to `inputStyle` props, but I can't override the `width` in my class, because it is always passed into `style` of the `<input>` elements.
So either the `style` should not be applied when there is a className in `inputStyle`, or there should be a prop to turn the default style off, something like `isDefaultInputStyleApplied: boolean` with a `true` default.

**Comment by apollonian** [comment]
> So either the style should not be applied when there is a className in inputStyle, or there should be a prop to turn the default style off, something like isDefaultInputStyleApplied: boolean with a true default.

@rtrembecky Considering something along similar lines for the next major release! Eliminating the limitations that `inputStyle` brings by doubling as a className prop is something to be addressed too. So, I'm thinking we could split it into `inputStyle` and `inputClassName`, where the `inputStyle` prop only takes a CSS style object and `inputClassName` applies class names to the input(s).

**Comment by mdsadiq** [comment]
@apollonian is this change already in the release ? is it something that we could contribute ?

**Comment by prateek3255** [comment]
You can now fully customize the input component with v3. Check the docs for more info

**Comment by Supersmf** [comment]
you can remove style property from renderInput function
`renderInput={({ style, ...props }) => <input {...props} />}`
