### ISSUE TITLE
Pasting from clipboard on Android

### ISSUE THREAD

**Issue by es1831** [devfolioco/react-otp-input#280]
- **Describe the Feature Request**
Having an issue pasting a code from clipboard on android

https://user-images.githubusercontent.com/8410389/114436022-de2db500-9b92-11eb-9b6a-45bf0624ebcd.mp4

- **Describe Preferred Solution**
should behave the same as pasting, where the numbers are auto-filled once you click on the number

**Comment by AzurDrive** [comment]
Hello!

Any updates on this?
Cause same problems for iOS / Android auto-paste from SMS - code is not being parsed correctly and only first number is pasted.

**Comment by DeadEnglish** [comment]
Also running into this issue on Android, pasting from clipboard works but pasting from sms messages doesn't.

**Comment by Janviba911** [comment]
I am facing same issue which was posted by @AzurDrive, Please give a solution as soon as possible @ajayns, @apollonian

**Comment by AzurDrive** [comment]
@DeadEnglish  @Janviba911 yo guys, i can share my "hack" and overall thoughts on this library.
So, you see, ths component renders 4 separate inputs, 1st input is auto-focused (default), and when you try to paste code from sms, it is pasted in this 1st input, but only 1st digit, cause maxLength is 1.
Then all the rest logic - proceed inputing to other 3 inputs - doesnt work here like with pasting from clipboard.
Because code got pasted directly to rendered input, not to React OTP component (somehow).

So my solution.
Make <input /> on top of react-otp (place them in one container). Input should be numeric-based, maxLength 4, autofocused, controllable. color and background are transparent.
also set react-otp to pointerEvents: none. Share the contolled input to react.state and pass that value to react-otp component too.
all the rest styles are on yours.

**Comment by LuisValgoi** [comment]
@AzurDrive can you share the code?

**Comment by ritikbanger** [comment]
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by dariohirsch** [comment]
Hi! any update on this issue? Im facing the same problem. Thanks!!

**Comment by prateek3255** [comment]
@es1831 Can you check if this issue still exists with v3. If yes would you like take this up?

**Comment by chocodate** [comment]
It works for ios chrome but such a screen appears. When I hit close it copies all the code. Could the console be forgotten somewhere?

![IMG_0993](https://user-images.githubusercontent.com/120307937/229111403-2ff55938-0d25-4e29-9c23-ac93f585af65.png)

**Comment by hogiyogi597** [comment]
I believe I have a fix for this in this PR here: https://github.com/devfolioco/react-otp-input/pull/428

**Comment by prateek3255** [comment]
This was fixed with #428
