### ISSUE TITLE
Border color change when OTP input box selected

### ISSUE THREAD

**Issue by AnushkaTyagi26** [devfolioco/react-otp-input#409]
- Whenever we select one input value in OTP its border color changes to black color which is default color. Add some function please to change color of borders when hover and selected. It will be a great help for my organization.

-If there is a function present in API which I haven't be able to understand to change color of the border, then please provide me the solution please. 

-I have attached the image from my project please check it and help me out with the solution.

Anushka Tyagi

![otp](https://github.com/devfolioco/react-otp-input/assets/130362081/5133dcd2-1f20-4367-96aa-efb80cf2a843)

**Comment by prateek3255** [comment]
Hey @AnushkaTyagi26 hope you are using v3 version of the library because the library no longer controls the styling aspect of your inputs, the inputs are passed as a render prop to the library by the library consumers so you can [style the input](https://github.com/devfolioco/react-otp-input#basic-usage) on focus as you want
