### ISSUE TITLE
Letter accepted even if isInputNum is true

### ISSUE THREAD

**Issue by Rishabh510** [devfolioco/react-otp-input#50]
- **Steps to reproduce the issue**:
In the demo site, when isInputNum is true, still you can enter unlimited amount of the letter 'e' in the boxes. Clear button doesn't work after that.

- **Relevant error messages and/or screenshots**:
![image](https://user-images.githubusercontent.com/42823059/66156195-d35da000-e63e-11e9-85d2-ed6f95cd2a5d.png)

**Comment by xitter** [comment]
I would like to like to take this up.

**Comment by robintom** [comment]
This is how the [HTML Spec](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)) says it works. So for our instance since the input box accepts numbers which includes floating point numbers the Demo site field would accept all these : "e", ".", "+", "-" and not just "e" as this issue suggests.

I think what we could do is sanitize the input in the library itself, using a regular expression. Can i give this a go ? @apollonian

**Comment by apollonian** [comment]
@robintom Got it. I see that there are a fixes suggested in a couple of open PRs (Including one that implements a regexp testing).
