### ISSUE TITLE
First Input is not accepting zero as value

### ISSUE THREAD

**Issue by shreyvijayvargiya** [devfolioco/react-otp-input#71]
- **Describe the Feature Request**

- **Describe Preferred Solution**
The First Input element in OTP input is not accepting the zero as a number. Rest all the remaining input takes zero.

**Comment by arvind0598** [comment]
Works for me on the demo site. I'm able to put 0 anywhere I want to.

**Comment by raghavpatnecha** [comment]
You need to take num as `'' + value;`

**Comment by RGKrish183** [comment]
@raghavpatnecha give me proper examples, i have also facing this issue,.. my code is below

```
   <OtpInput
     inputStyle={classes.rpc_htextField}
     numInputs={6}
     isInputNum={true}
     value={oldPin2Fa}
     onChange={otp => this.handleChange(otp, 'oldPin2Fa')}
     />

```

Thanks,
GopalaKrishnan.R

**Comment by robbiehanson** [comment]
I'm also seeing this same problem on the demo site.

Steps to reproduce:
- Go to demo site
- Put a checkmark in the box for `isInputNum `
- Attempt to put a zero in the first field

**Comment by gauravkk22** [comment]
I am also facing the same issue. i am not able to take zero in my first input??

**Comment by prograk** [comment]
It's because isInputNum is set to true if you change to String it works but than it accepts all other value.

I did a work around where I kept isInputNum to false and checked if input is not number replace it with blank space than it accepts 0 as first character but again another issue comes in i.e cursor goes to next box.
